name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: setup python for uploader
        uses: actions/setup-python@v4
        with:
          python-version : '3.10'
          cache: pip
      - name: build
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace clean build
      - name: upload
        if: always() && github.ref == 'refs/heads/master' && (steps.gradle.outcome == 'success' || steps.gradle.outcome == 'failure')
        run: |
          pip install requests
          python ../../../../scripts/upload_dev.py --result ${{ steps.gradle.outcome }} --webhook ${{ secrets.DISCORD_DEV_FEED_WEBHOOK }}
        working-directory: projects/pswg/build/libs
        env:
          BUILD_NUMBER: ${{ github.run_number }}
